### PR TITLE
swap buttons

### PR DESCRIPTION
**Pull request by ardadem**
By ru1dev https://forum.xda-developers.com/mi-5s/development/mod-swap-buttons-xiaomi-mi-5s-t3561095

### CODE REVIEW

**Comment by luk1337** [comment]
This is not needed. We have a setting for that.

**Comment by ardadem** [comment]
where? I have not seen in settings > buttons.

**Comment by luk1337** [comment]
Are you using official TWRP?

**Comment by ardadem** [comment]
yes

**Comment by luk1337** [comment]
Then you should have "Additional buttons" below Buttons in Settings.

**Comment by luk1337** [comment]
Did it work?

**Comment by ardadem** [comment]
okay, i found. I can close request if you want?

**Comment by luk1337** [comment]
Yeah, close it.

**Pull request closed without merging**
