### PR TITLE
Update README.mkdn

### PR DESCRIPTION
**Pull request by stefanfelix**
Minor changes to device info.

### CODE REVIEW

**Comment by luk1337** [comment]
What about doing something other than editing a readme? Also use gerrit, we don't accept pull requests via github.

**Comment by zjy2200656** [comment]
volte is work on audio calling, but doesn't work on video calling and no volte sign on status bar

**Comment by zjy2200656** [comment]
Bluetooth use too much battery

**Comment by lineageos-gerrit** [comment]
Hi there;
This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Pull request closed without merging**
